### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by dxp10** [kissy24/go-notion#1]
Hi friend, could you rate my repositories and I'll rate yours at the same time? Thanks!

**Comment by kissy24** [comment]
Hi dxp10 san, thank you for offering to evaluate my repository, but I don't think I am interested in an exchange of evaluations at this time. However, I appreciate your willingness to help.

**Comment by kissy24** [comment]
Hi dxp10 san, I will close this issue as it is unrelated to the content of this repository. Thanks.
